{% set name = "pyreadr" %}
{% set version = "0.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95f677019567b86d49e3f60c6c67edd1f8d2afe7f2aac3b419d90c98bfa42890

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler("m2w64_c") }}  # [win]
    - {{ compiler('c') }}  # [not win]
  host:
    - python
    - pip
    - cython
    - m2w64-toolchain  # [win]
    - libpython  # [win]
    - bzip2  # [not win]
    - zlib
  run:
    - python
    - pandas
    - m2w64-gcc-libs  # [win]
    - bzip2  # [not win]

test:
  imports:
    - pyreadr

about:
  home: https://github.com/ofajardo/pyreadr
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE.txt
  summary: read R RData and Rds files into pandas data frames
  description: |
    Python package to read and write R RData and Rds files into/from pandas dataframes. No R or other external dependencies required.
  doc_url: https://github.com/ofajardo/pyreadr
  dev_url: https://github.com/ofajardo/pyreadr

extra:
  recipe-maintainers:
    - ofajardo
