{% set name = "pyreadr" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 71517866240ed195e7933ed9c47129e738d6f23c3269556f1db4037554ecf455

build:
  number: 3
  skip: true  # [python_impl == 'pypy']
  skip: true  # [py<35]
  script:
    - set DISTUTILS_USE_SDK=1    # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler("m2w64_c") }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ compiler('c') }}  # [not win]
    - {{ stdlib("c") }}    # [not win]
    - conda-gcc-specs   # [win]
  host:
    - python
    - pip
    - cython
    - setuptools
    - libpython  # [win]
    - bzip2  
    - zlib
    - liblzma-devel
  run:
    - python
    - pandas

test:
  imports:
    - pyreadr

about:
  home: https://github.com/ofajardo/pyreadr
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE.txt
  summary: read R RData and Rds files into pandas data frames
  description: |
    Python package to read and write R RData and Rds files into/from pandas dataframes. No R or other external dependencies required.
  doc_url: https://github.com/ofajardo/pyreadr
  dev_url: https://github.com/ofajardo/pyreadr

extra:
  recipe-maintainers:
    - ofajardo
