{% set name = "pyreadr" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3243f0f7107c47a193508f79f39f22310f66352f5f5ee18bb0208ceebfd84fb6

build:
  number: 0
  script:
    - set DISTUTILS_USE_SDK=1    # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    # uses m2w64 toolchain on windows, see conda_build_config.yaml
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - conda-gcc-specs   # [win]
  host:
    - python
    - pip
    - cython
    - setuptools
    - distutils-activate-mingw  # [win]
    - bzip2
    - zlib
    - liblzma-devel
  run:
    - python
    - pandas

test:
  imports:
    - pyreadr

about:
  home: https://github.com/ofajardo/pyreadr
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE.txt
  summary: read R RData and Rds files into pandas data frames
  description: |
    Python package to read and write R RData and Rds files into/from pandas dataframes. No R or other external dependencies required.
  doc_url: https://github.com/ofajardo/pyreadr
  dev_url: https://github.com/ofajardo/pyreadr

extra:
  recipe-maintainers:
    - ofajardo
